#ifndef DEFINITIONS_H
#define DEFINITIONS_H

//error codes
#define FILE_NOT_FOUND -1
#define UNABLE_TO_CLOSE -2
#define UNABLE_TO_READ_TEMPLATE -3
#define UNABLE_TO_OPEN_OUTPUT -4
#define UNEQUAL_CHARACTER_COUNT -5
#define UNABLE_TO_WRITE_OUTPUT -6
#define INVALID_ARGUMENTS -7
#define UNABLE_TO_COPY_CONTENTS -8
#define UNABLE_TO_ALLOC -9
#define NO_PREVIOUS_BUFFER -10
#define NOT_ENOUGH_BUFFER_SPACE -11

#endif