#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define FILE_NOT_FOUND -1
#define UNABLE_TO_CLOSE -2
#define UNABLE_TO_READ_TEMPLATE -3
#define UNABLE_TO_OPEN_OUTPUT -4
#define UNEQUAL_CHARACTER_COUNT -5

#endif